package interfaces

// type Rows interface {
// 	Scan(dest ...interface{}) error
// 	Next() bool
// 	Close() error
// }

// // A Result summarizes an executed SQL command.
// type Result interface {
// 	// LastInsertId returns the integer generated by the database
// 	LastInsertId() (int64, error)
// 	// RowsAffected returns the number of rows affected
// 	RowsAffected() (int64, error)
// }

// type SomeRepo struct {
// 	storageHandler  SomeHandler
// }

// type SomePostsRepo SomeRepo

// func NewSomePostsRepo(handler SomeHandler) *SomePostsRepo {
// 	postrepo := &SomePostsRepo{
// 		storageHandler: handler,
// 	}
// 	return postrepo
// }

// func (spr *SomePostsRepo) FindByID(id string) (domain.PostInBlog, error) {
// 	q := id
// 	post := domain.PostInBlog{}
// 	rows, err := spr.storageHandler.Query(q)
// 	if !rows.Next() {
// 		err = fmt.Errorf("nothing not found for PostID=%s", id)
// 		return post, err
// 	}
// 	err = rows.Scan(&post.ID, &post.Title)
// 	return post, nil
// }
